sudo: required
services:
        - docker
before_install:
        - docker build -t scratbyte/docker-react -f Dockerfile.dev .
script:
        - docker run scratbyte/docker-react npm run test -- --coverage
